### ISSUE TITLE
Share k3d Dockerfile?

### ISSUE THREAD

**Issue by erichorwath** [kubernetes101/kubecon2022#17]
Would you be able to share the k3d Dockerfile used in this repo? :-)

**Comment by mmphego** [comment]
> Would you be able to share the k3d Dockerfile used in this repo? :-)

Located here -> https://github.com/kubernetes101/kubecon2022/blob/main/.devcontainer/Dockerfile

**Comment by nieebel** [comment]
```
FROM ghcr.io/kubernetes101/k3d:latest
```
And what is in there?

**Comment by erichorwath** [comment]
```
FROM ghcr.io/kubernetes101/k3d:latest
```
And what is in there?

**Comment by bartr** [comment]
That image (and others) are built here: https://github.com/cse-labs/codespaces-images
